// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/:key": {
    params: {
      "key": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/login" | "/join" | "/logout" | "/healthcheck" | "/:key";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
  "./routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "./routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "./routes/$key.tsx": {
    id: "routes/$key";
    page: "/:key";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/./routes/index.tsx");
  "routes/admin": typeof import("./app/./routes/admin.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/join": typeof import("./app/./routes/join.tsx");
  "routes/logout": typeof import("./app/./routes/logout.tsx");
  "routes/healthcheck": typeof import("./app/./routes/healthcheck.tsx");
  "routes/$key": typeof import("./app/./routes/$key.tsx");
};